# Generated by Django 4.0.4 on 2022-05-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='projects.category'),
            preserve_default=False,
        ),
    ]
