# Generated by Django 4.0.4 on 2022-05-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dontation',
            old_name='total_target',
            new_name='donation_amount',
        ),
    ]
