# Generated by Django 4.0.4 on 2022-05-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_total_target_dontation_donation_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dontation',
            old_name='user',
            new_name='donator',
        ),
    ]
