# Generated by Django 4.0.4 on 2022-05-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_project_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentreport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dontation',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='dontation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrate',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projecttag',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category'),
        ),
    ]
