# Generated by Django 4.0.4 on 2022-05-09 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_dontation_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrate',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
