# Generated by Django 4.0.4 on 2022-05-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectrate_value'),
        ('projects', '0006_commentreply'),
    ]

    operations = [
    ]
